/* See COPYRIGHT for copyright information. */

#include <inc/x86.h>
#include <inc/mmu.h>
#include <inc/error.h>
#include <inc/string.h>
#include <inc/assert.h>

#include <kern/monitor.h>
#include <kern/pmap.h>
#include <kern/kclock.h>
#include <kern/env.h>
#include <kern/cpu.h>

#include "mem-config.h"

// These variables are set by i386_detect_memory()
size_t npages;			// Amount of physical memory (in pages)
static size_t npages_basemem;	// Amount of base memory (in pages)

// These variables are set in mem_init()
pde_t *kern_pgdir;		// Kernel's initial page directory
struct PageInfo *pages;		// Physical page state array
static struct PageInfo *page_free_list;	// Free list of physical pages

#define SEGTREE_SIZE (1 << 20)
static unsigned char *page_segtree;  // Heap-style segment tree

static void segtree_modify(int pos, int val) {
	pos += SEGTREE_SIZE;
	page_segtree[pos] = val;
	while (pos > 1) {
		page_segtree[pos >> 1] = page_segtree[pos] & page_segtree[pos ^ 1];
		pos >>= 1;
	}
}

static int segtree_get(int pos) {
	return page_segtree[pos + SEGTREE_SIZE];
}

static int segtree_alloc_left() {
	if (page_segtree[1] == 1) {
		return -1;
	}
	int p = 1;
	while (p < SEGTREE_SIZE) {
		p <<= 1;
		p += page_segtree[p];
	}
	p -= SEGTREE_SIZE;
	segtree_modify(p, 1);
	return p;
}

static int segtree_alloc_right() {
	if (page_segtree[1] == 1) {
		return -1;
	}
	int p = 1;
	while (p < SEGTREE_SIZE) {
		p = p * 2 + 1;
		p -= page_segtree[p];
	}
	p -= SEGTREE_SIZE;
	segtree_modify(p, 1);
	return p;
}

static void segtree_free(int p) {
	segtree_modify(p, 0);
}


// --------------------------------------------------------------
// Detect machine's physical memory setup.
// --------------------------------------------------------------

static int
nvram_read(int r)
{
	return mc146818_read(r) | (mc146818_read(r + 1) << 8);
}

static void
i386_detect_memory(void)
{
	size_t basemem, extmem, ext16mem, totalmem;

	// Use CMOS calls to measure available base & extended memory.
	// (CMOS calls return results in kilobytes.)
	basemem = nvram_read(NVRAM_BASELO);
	extmem = nvram_read(NVRAM_EXTLO);
	ext16mem = nvram_read(NVRAM_EXT16LO) * 64;

	// Calculate the number of physical pages available in both base
	// and extended memory.
	if (ext16mem)
		totalmem = 16 * 1024 + ext16mem;
	else if (extmem)
		totalmem = 1 * 1024 + extmem;
	else
		totalmem = basemem;
	
	int max = MAX_SYSTEM_MEMORY;  // GG!!!
	if(totalmem > max)
		totalmem = max;
	#ifdef FIXED_SYSTEM_MEMORY
	totalmem = FIXED_SYSTEM_MEMORY;
	#endif

	npages = totalmem / (PGSIZE / 1024);
	npages_basemem = basemem / (PGSIZE / 1024);

	cprintf("Physical memory: %uK available, base = %uK, extended = %uK\n",
		totalmem, basemem, totalmem - basemem);
}


// --------------------------------------------------------------
// Set up memory mappings above UTOP.
// --------------------------------------------------------------

static void mem_init_mp(void);
static void check_page_free_list(bool only_low_memory);
static void check_page_alloc(void);
static void check_kern_pgdir(void);
static physaddr_t check_va2pa(pde_t *pgdir, uintptr_t va);
static void check_page(void);
static void check_page_installed_pgdir(void);

// This simple physical memory allocator is used only while JOS is setting
// up its virtual memory system.  page_alloc() is the real allocator.
//
// If n>0, allocates enough pages of contiguous physical memory to hold 'n'
// bytes.  Doesn't initialize the memory.  Returns a kernel virtual address.
//
// If n==0, returns the address of the next free page without allocating
// anything.
//
// If we're out of memory, boot_alloc should panic.
// This function may ONLY be used during initialization,
// before the page_free_list list has been set up.
static void *
boot_alloc(uint32_t n)
{
	static char *nextfree;	// virtual address of next byte of free memory
	char *result;

	// Initialize nextfree if this is the first time.
	// 'end' is a magic symbol automatically generated by the linker,
	// which points to the end of the kernel's bss segment:
	// the first virtual address that the linker did *not* assign
	// to any kernel code or global variables.
	if (!nextfree) {
		extern char end[];
		nextfree = ROUNDUP((char *) end, PGSIZE);
	}

	// Allocate a chunk large enough to hold 'n' bytes, then update
	// nextfree.  Make sure nextfree is kept aligned
	// to a multiple of PGSIZE.
	//
	// LAB 2: Your code here.
	void *ret = nextfree;
	nextfree = ROUNDUP(nextfree + n, PGSIZE);
	cprintf("boot_alloc: %p / %p\n", nextfree, 0xf2000000);
	if (nextfree >= (char *) 0xf2000000)
		panic("boot_alloc: out of memory");
	return ret;
}

static int inited = 0;

// Set up a two-level page table:
//    kern_pgdir is its linear (virtual) address of the root
//
// This function only sets up the kernel part of the address space
// (ie. addresses >= UTOP).  The user part of the address space
// will be setup later.
//
// From UTOP to ULIM, the user is allowed to read but not write.
// Above ULIM the user cannot read or write.
void
mem_init(void)
{
	uint32_t cr0;
	size_t n;

	// Find out how much memory the machine has (npages & npages_basemem).
	i386_detect_memory();

	// Remove this line when you're ready to test this function.
	// panic("mem_init: This function is not finished\n");

	//////////////////////////////////////////////////////////////////////
	// create initial page directory.
	kern_pgdir = (pde_t *) boot_alloc(PGSIZE);
	memset(kern_pgdir, 0, PGSIZE);
	
	// kern_phys_pgdir = (pde_t *) boot_alloc(PGSIZE);
	// memset(kern_phys_pgdir, 0, PGSIZE);

	//////////////////////////////////////////////////////////////////////
	// Recursively insert PD in itself as a page table, to form
	// a virtual page table at virtual address UVPT.
	// (For now, you don't have understand the greater purpose of the
	// following line.)

	// Permissions: kernel R, user R
	kern_pgdir[PDX(UVPT)] = PADDR(kern_pgdir) | PTE_U | PTE_P;

	//////////////////////////////////////////////////////////////////////
	// Allocate an array of npages 'struct PageInfo's and store it in 'pages'.
	// The kernel uses this array to keep track of physical pages: for
	// each physical page, there is a corresponding struct PageInfo in this
	// array.  'npages' is the number of physical pages in memory.  Use memset
	// to initialize all fields of each struct PageInfo to 0.
	// Your code goes here:
	size_t pages_size = npages * sizeof(struct PageInfo);
	pages = boot_alloc(pages_size);
	memset(pages, 0, pages_size);

	//////////////////////////////////////////////////////////////////////
	// Make 'envs' point to an array of size 'NENV' of 'struct Env'.
	// LAB 3: Your code here.
	size_t envs_size = NENV * sizeof(struct Env);
	envs = boot_alloc(envs_size);
	memset(envs, 0, envs_size);

	//////////////////////////////////////////////////////////////////////
	// Now that we've allocated the initial kernel data structures, we set
	// up the list of free physical pages. Once we've done so, all further
	// memory management will go through the page_* functions. In
	// particular, we can now map memory using boot_map_region
	// or page_insert
	page_init();

	// check_page_free_list(1);
	// check_page_alloc();
	// check_page();

	//////////////////////////////////////////////////////////////////////
	// Now we set up virtual memory

	//////////////////////////////////////////////////////////////////////
	// Map 'pages' read-only by the user at linear address UPAGES
	// Permissions:
	//    - the new image at UPAGES -- kernel R, user R
	//      (ie. perm = PTE_U | PTE_P)
	//    - pages itself -- kernel RW, user NONE
	// Your code goes here:
	
	//boot_map_region(pde_t *pgdir, uintptr_t va, size_t size, physaddr_t pa, int perm)
	//int bn = ROUNDUP(pages_size, PGSIZE) / PGSIZE;
	boot_map_region(kern_pgdir, UPAGES, ROUNDUP(pages_size, PGSIZE), PADDR(pages), PTE_U | PTE_P);
	//page_insert(kern_pgdir, pa2page(PADDR(&pages)), (void *) ((size_t) (&pages) >> PGSHIFT << PGSHIFT), PTE_W | PTE_P);
	//for(int i = 0; i < bn; ++i)
	//	page_insert(kern_pgdir, pa2page(PADDR(pages)) + i, (void *) (UPAGES + i * PGSIZE), PTE_U | PTE_P);

	//////////////////////////////////////////////////////////////////////
	// Map the 'envs' array read-only by the user at linear address UENVS
	// (ie. perm = PTE_U | PTE_P).
	// Permissions:
	//    - the new image at UENVS  -- kernel R, user R
	//    - envs itself -- kernel RW, user NONE
	// LAB 3: Your code here.
	//cprintf("vaddr envs %p\n", envs);
	boot_map_region(kern_pgdir, UENVS, ROUNDUP(envs_size, PGSIZE), PADDR(envs), PTE_U | PTE_P);
	// cprintf("uenvs %p size %p pa %p\n", UENVS, ROUNDUP(envs_size, PGSIZE), PADDR(envs));
	// cprintf("kern walk %p %p\n", pgdir_walk(kern_pgdir, (void *) 0xeec60000, 0), *pgdir_walk(kern_pgdir, (void *) 0xeec60000, 0));
	// cprintf("kern walk %p %p\n", pgdir_walk(kern_pgdir, (void *) 0xeec60048, 0), *pgdir_walk(kern_pgdir, (void *) 0xeec60048, 0));
	//while(1);

	//////////////////////////////////////////////////////////////////////
	// Use the physical memory that 'bootstack' refers to as the kernel
	// stack.  The kernel stack grows down from virtual address KSTACKTOP.
	// We consider the entire range from [KSTACKTOP-PTSIZE, KSTACKTOP)
	// to be the kernel stack, but break this into two pieces:
	//     * [KSTACKTOP-KSTKSIZE, KSTACKTOP) -- backed by physical memory
	//     * [KSTACKTOP-PTSIZE, KSTACKTOP-KSTKSIZE) -- not backed; so if
	//       the kernel overflows its stack, it will fault rather than
	//       overwrite memory.  Known as a "guard page".
	//     Permissions: kernel RW, user NONE
	// Your code goes here:
	
	boot_map_region(kern_pgdir, KSTACKTOP - KSTKSIZE, KSTKSIZE, PADDR(bootstack), PTE_P | PTE_W);
	//struct PageInfo *bpi = pa2page(PADDR(bootstack));
	//for(void *i = (void *) (KSTACKTOP - KSTKSIZE); i != (void *) KSTACKTOP; i += PGSIZE)
	//	page_insert(kern_pgdir, bpi++, i, PTE_P | PTE_W);

	//////////////////////////////////////////////////////////////////////
	// Map all of physical memory at KERNBASE.
	// Ie.  the VA range [KERNBASE, 2^32) should map to
	//      the PA range [0, 2^32 - KERNBASE)page2pa
	// We might not have 2^32 - KERNBASE bytes of physical memory, but
	// we just set up the mapping anyway.
	// Permissions: kernel RW, user NONE
	// Your code goes here:
	
	boot_map_region(kern_pgdir, KERNBASE, -KERNBASE, 0, PTE_P | PTE_W);
	//bpi = pages;
	//for(void *i = (void *) KERNBASE; i; i += PGSIZE)
	//	page_insert(kern_pgdir, bpi++, i, PTE_P | PTE_W);

	// Initialize the SMP-related parts of the memory map
	mem_init_mp();

	// Check that the initial page directory has been set up correctly.
	// check_kern_pgdir();

	// Switch from the minimal entry page directory to the full kern_pgdir
	// page table we just created.	Our instruction pointer should be
	// somewhere between KERNBASE and KERNBASE+4MB right now, which is
	// mapped the same way by both page tables.
	//
	// If the machine reboots at this point, you've probably set up your
	// kern_pgdir wrong.
	lcr3(PADDR(kern_pgdir));

	// check_page_free_list(0);

	// entry.S set the really important flags in cr0 (including enabling
	// paging).  Here we configure the rest of the flags that we care about.
	cr0 = rcr0();
	cr0 |= CR0_PE|CR0_PG|CR0_AM|CR0_WP|CR0_NE|CR0_MP;
	cr0 &= ~(CR0_TS|CR0_EM);
	lcr0(cr0);

	// Some more checks, only possible after kern_pgdir is installed.
	// check_page_installed_pgdir();
	
	inited = 1;
}

// Modify mappings in kern_pgdir to support SMP
//   - Map the per-CPU stacks in the region [KSTACKTOP-PTSIZE, KSTACKTOP)
//
static void
mem_init_mp(void)
{
	// Map per-CPU stacks starting at KSTACKTOP, for up to 'NCPU' CPUs.
	//
	// For CPU i, use the physical memory that 'percpu_kstacks[i]' refers
	// to as its kernel stack. CPU i's kernel stack grows down from virtual
	// address kstacktop_i = KSTACKTOP - i * (KSTKSIZE + KSTKGAP), and is
	// divided into two pieces, just like the single stack you set up in
	// mem_init:
	//     * [kstacktop_i - KSTKSIZE, kstacktop_i)
	//          -- backed by physical memory
	//     * [kstacktop_i - (KSTKSIZE + KSTKGAP), kstacktop_i - KSTKSIZE)
	//          -- not backed; so if the kernel overflows its stack,
	//             it will fault rather than overwrite another CPU's stack.
	//             Known as a "guard page".
	//     Permissions: kernel RW, user NONE
	//
	// LAB 4: Your code here:
	//boot_map_region(pde_t *pgdir, uintptr_t va, size_t size, physaddr_t pa, int perm)
	for(int i = 0; i < NCPU; i++)
	{
		uintptr_t kstacktop_i = KSTACKTOP - i * (KSTKSIZE + KSTKGAP);
		boot_map_region(kern_pgdir, kstacktop_i - KSTKSIZE, KSTKSIZE, PADDR(percpu_kstacks[i]), PTE_P | PTE_W);
	}
}

// --------------------------------------------------------------
// Tracking of physical pages.
// The 'pages' array has one 'struct PageInfo' entry per physical page.
// Pages are reference counted, and free pages are kept on a linked list.
// --------------------------------------------------------------

//
// Initialize page structure and memory free list.
// After this is done, NEVER use boot_alloc again.  ONLY use the page
// allocator functions below to allocate and deallocate physical
// memory via the page_free_list.
//
void
page_init(void)
{
	// LAB 4:
	// Change your code to mark the physical page at MPENTRY_PADDR
	// as in use

	// The example code here marks all physical pages as free.
	// However this is not truly the case.  What memory is free?
	//  1) Mark physical page 0 as in use.
	//     This way we preserve the real-mode IDT and BIOS structures
	//     in case we ever need them.  (Currently we don't, but...)
	//  2) The rest of base memory, [PGSIZE, npages_basemem * PGSIZE)
	//     is free.
	//  3) Then comes the IO hole [IOPHYSMEM, EXTPHYSMEM), which must
	//     never be allocated.
	//  4) Then extended memory [EXTPHYSMEM, ...).
	//     Some of it is in use, some is free. Where is the kernel
	//     in physical memory?  Which pages are already in use for
	//     page tables and other data structures?
	//
	// Change the code to reflect this.
	// NB: DO NOT actually touch the physical memory corresponding to
	// free pages!
	
	cprintf("ready to alloc segtree\n");
	page_segtree = boot_alloc(SEGTREE_SIZE * 2);
	cprintf("alloc segtree ok\n");
	memset(page_segtree, 0x01, SEGTREE_SIZE * 2);
	
	assert(MPENTRY_PADDR % PGSIZE == 0);
	for(int i = npages - 1; i >= 0; i--)
		if(i == 0 || ((uint32_t) i * PGSIZE >= IOPHYSMEM && (uint32_t) i * PGSIZE < EXTPHYSMEM + (64 << 20)) || i * PGSIZE == MPENTRY_PADDR)
		{
			pages[i].pp_ref = 233; // 233?
		}
		else if(npages - i <= JUDGE_PAGES_COUNT)
		{
			pages[i].pp_ref = 666;
		}
		else
		{
			/*pages[i].pp_ref = 0;
			pages[i].pp_link = page_free_list;
			page_free_list = &pages[i];*/
			pages[i].pp_ref = 0;
			segtree_modify(i, 0);
		}
	cprintf("modify done\n");
}

struct PageInfo *
get_first_judge_page()
{
	return pages + npages - JUDGE_PAGES_COUNT;
}

//
// Allocates a physical page.  If (alloc_flags & ALLOC_ZERO), fills the entire
// returned physical page with '\0' bytes.  Does NOT increment the reference
// count of the page - the caller must do these if necessary (either explicitly
// or via page_insert).
//
// Be sure to set the pp_link field of the allocated page to NULL so
// page_free can check for double-free bugs.
//
// Returns NULL if out of free memory.
//
// Hint: use page2kva and memset
struct PageInfo *
pte_page_alloc(void)
{
	int pp_begin = (EXTPHYSMEM + (32 << 20)) / PGSIZE;
	int pp_end   = (EXTPHYSMEM + (64 << 20)) / PGSIZE;
	for(int i = pp_begin; i < pp_end; ++i)
		if(pages[i].pp_ref == 233)
		{
			// cprintf("pte alloc %p\n", i * PGSIZE);
			struct PageInfo *ret = pages + i;
			// cprintf("gg %p\n", page2kva(ret));
			memset(page2kva(ret), 0, PGSIZE);
			// cprintf("pte asdf %p\n", i * PGSIZE);
			return ret;
		}
	return NULL;
}

static struct PageInfo * segtree_alloc_page_left() {
	int id = segtree_alloc_left();
	if (id == -1) {
		return NULL;
	}
	return pages + id;
}

static struct PageInfo * segtree_alloc_page_right() {
	int id = segtree_alloc_right();
	if (id == -1) {
		return NULL;
	}
	return pages + id;
}

static struct PageInfo * segtree_alloc_page_spec(struct PageInfo *pp) {
	int id = pp - pages;
	if (segtree_get(id) == 1) {
		return NULL;
	}
	segtree_modify(id, 1);
	return pp;
}

static void segtree_free_page(struct PageInfo *pp) {
	int id = pp - pages;
	segtree_free(id);
}

struct PageInfo *
page_alloc(int alloc_flags)
{
	// Fill this function in
	/*if(!page_free_list)
		return NULL;
	struct PageInfo *ret = page_free_list;
	page_free_list = ret->pp_link;
	ret->pp_link = NULL;*/
	struct PageInfo *ret;
	if ((contestant_env && curenv == contestant_env) || !inited) {
		ret = segtree_alloc_page_left();
	} else {
		ret = segtree_alloc_page_right();
	}
	if (!ret) return NULL;
	if(alloc_flags & ALLOC_ZERO)
	{
		if((ret - pages) * PGSIZE < 0x10000000u)
			memset(page2kva(ret), 0, PGSIZE);
		else
		{
			// cprintf("ret = %d | %p\n", ret - pages, (ret - pages) * PGSIZE);
			boot_map_region(kern_pgdir, PGSIZE, PGSIZE, (ret - pages) * PGSIZE, PTE_W);
			lcr3(PADDR(kern_pgdir));
			invlpg((void *) PGSIZE);
			asm volatile("");
			memset((void *) PGSIZE, 0, PGSIZE);
		}
	}
	//cprintf("alloc %d\n", ret->pp_ref);
	//mon_backtrace(0, NULL, NULL);
	return ret;
}

struct PageInfo *
page_alloc_spec(int alloc_flags, struct PageInfo *pp)
{
	// Fill this function in
	/*if(!page_free_list)
		return NULL;
	struct PageInfo *ret = page_free_list;
	page_free_list = ret->pp_link;
	ret->pp_link = NULL;*/
	struct PageInfo *ret;
	ret = segtree_alloc_page_spec(pp);
	if (!ret) return NULL;
	if(alloc_flags & ALLOC_ZERO)
	{
		if((ret - pages) * PGSIZE < 0x10000000u)
			memset(page2kva(ret), 0, PGSIZE);
		else
		{
			// cprintf("ret = %d | %p\n", ret - pages, (ret - pages) * PGSIZE);
			boot_map_region(kern_pgdir, PGSIZE, PGSIZE, (ret - pages) * PGSIZE, PTE_W);
			lcr3(PADDR(kern_pgdir));
			invlpg((void *) PGSIZE);
			asm volatile("");
			memset((void *) PGSIZE, 0, PGSIZE);
		}
	}
	//cprintf("alloc %d\n", ret->pp_ref);
	//mon_backtrace(0, NULL, NULL);
	return ret;
}

//
// Return a page to the free list.
// (This function should only be called when pp->pp_ref reaches 0.)
//
void
page_free(struct PageInfo *pp)
{
	// Fill this function in
	// Hint: You may want to panic if pp->pp_ref is nonzero or
	// pp->pp_link is not NULL.
	if(pp->pp_ref)
		panic("pp_ref nonzero when free\n");
	/*if(pp->pp_link)
		panic("double free?\n");
	pp->pp_link = page_free_list;
	page_free_list = pp;*/
	segtree_free_page(pp);
}

//
// Decrement the reference count on a page,
// freeing it if there are no more refs.
//
void
page_decref(struct PageInfo* pp)
{
	if (--pp->pp_ref == 0)
		page_free(pp);
}

// Given 'pgdir', a pointer to a page directory, pgdir_walk returns
// a pointer to the page table entry (PTE) for linear address 'va'.
// This requires walking the two-level page table structure.
//
// The relevant page table page might not exist yet.
// If this is true, and create == false, then pgdir_walk returns NULL.
// Otherwise, pgdir_walk allocates a new page table page with page_alloc.
//    - If the allocation fails, pgdir_walk returns NULL.
//    - Otherwise, the new page's reference count is incremented,
//	the page is cleared,
//	and pgdir_walk returns a pointer into the new page table page.
//
// Hint 1: you can turn a PageInfo * into the physical address of the
// page it refers to with page2pa() from kern/pmap.h.
//
// Hint 2: the x86 MMU checks permission bits in both the page directory
// and the page table, so it's safe to leave permissions in the page
// directory more permissive than strictly necessary.
//
// Hint 3: look at inc/mmu.h for useful macros that mainipulate page
// table and page directory entries.
//

pte_t *
pgdir_walk(pde_t *pgdir, const void *va, int create)
{
	// Fill this function in
	pde_t *ent = pgdir + PDX(va);
	//cprintf("walk *ent %p\n", *ent);
	if(*ent & PTE_P)
		return KADDR((physaddr_t) (PTX(va) + (pte_t *) PTE_ADDR(*ent)));
	else if(create)
	{
		struct PageInfo *pi = inited ? pte_page_alloc() : page_alloc(ALLOC_ZERO);
		if(!pi)
			return NULL;
		*ent = page2pa(pi) | PTE_P | PTE_W | PTE_U;
		++pi->pp_ref;
		return KADDR((physaddr_t) (PTX(va) + (pte_t *) PTE_ADDR(*ent)));
	}
	else
		return NULL;
}

//
// Map [va, va+size) of virtual address space to physical [pa, pa+size)
// in the page table rooted at pgdir.  Size is a multiple of PGSIZE, and
// va and pa are both page-aligned.
// Use permission bits perm|PTE_P for the entries.
//
// This function is only intended to set up the ``static'' mappings
// above UTOP. As such, it should *not* change the pp_ref field on the
// mapped pages.
//
// Hint: the TA solution uses pgdir_walk
void
boot_map_region(pde_t *pgdir, uintptr_t va, size_t size, physaddr_t pa, int perm)
{
	// Fill this function in
	for(size_t offset = 0; offset != size; offset += PGSIZE)
	{
		// if(inited) cprintf("map va %p to pa %p\n", va, pa);
		volatile pte_t *pte = pgdir_walk(pgdir, (const void *) (va + offset), 1);
		if(!pte)
			panic("map failed\n");
		*pte = (pa + offset) | perm | PTE_P;
		// if(inited) cprintf("*pte = %08x\n", *pte);
	}
}

//
// Map the physical page 'pp' at virtual address 'va'.
// The permissions (the low 12 bits) of the page table entry
// should be set to 'perm|PTE_P'.
//
// Requirements
//   - If there is already a page mapped at 'va', it should be page_remove()d.
//   - If necessary, on demand, a page table should be allocated and inserted
//     into 'pgdir'.
//   - pp->pp_ref should be incremented if the insertion succeeds.
//   - The TLB must be invalidated if a page was formerly present at 'va'.
//
// Corner-case hint: Make sure to consider what happens when the same
// pp is re-inserted at the same virtual address in the same pgdir.
// However, try not to distinguish this case in your code, as this
// frequently leads to subtle bugs; there's an elegant way to handle
// everything in one code path.
//
// RETURNS:
//   0 on success
//   -E_NO_MEM, if page table couldn't be allocated
//
// Hint: The TA solution is implemented using pgdir_walk, page_remove,
// and page2pa.
//
int
page_insert(pde_t *pgdir, struct PageInfo *pp, void *va, int perm)
{
	// Fill this function in
	tlb_invalidate(pgdir, va);
	pte_t *pte = pgdir_walk(pgdir, va, 0);
	bool remove = pte && (*pte & PTE_P);
	//bool spec = (pp->pp_ref == 1);
	if(remove)
	{
		//if(PTE_ADDR(*pte) == page2pa(pp))
		//	--pp->pp_ref;
		//else
		bool spec = (pp->pp_ref == 1 && PTE_ADDR(*pte) == page2pa(pp));
		page_remove(pgdir, va);
		//tlb_invalidate(pgdir, va);
		if(spec)
		{
			struct PageInfo *tmp = page_alloc_spec(0, pp);
			//cprintf("aha %p\n", tmp);
			assert(tmp == pp);
		}
	}
	pte = pgdir_walk(pgdir, va, 1);
	if(!pte)
		return -E_NO_MEM;
	*pte = page2pa(pp) | perm | PTE_P;
	++pp->pp_ref;
	return 0;
}

//
// Return the page mapped at virtual address 'va'.
// If pte_store is not zero, then we store in it the address
// of the pte for this page.  This is used by page_remove and
// can be used to verify page permissions for syscall arguments,
// but should not be used by most callers.
//
// Return NULL if there is no page mapped at va.
//
// Hint: the TA solution uses pgdir_walk and pa2page.
//
struct PageInfo *
page_lookup(pde_t *pgdir, void *va, pte_t **pte_store)
{
	// Fill this function in
	pte_t *pte = pgdir_walk(pgdir, va, 0);
	if(pte_store)
		*pte_store = pte;
	if(!pte || !(*pte & PTE_P))
		return NULL;
	if (PGNUM(PTE_ADDR(*pte)) < npages) {  // ONLY return valid pages, while others are not ref-counted
		return pa2page(PTE_ADDR(*pte));
	} else {
		return NULL;
	}
}

//
// Unmaps the physical page at virtual address 'va'.
// If there is no physical page at that address, silently does nothing.
//
// Details:
//   - The ref count on the physical page should decrement.
//   - The physical page should be freed if the refcount reaches 0.
//   - The pg table entry corresponding to 'va' should be set to 0.
//     (if such a PTE exists)
//   - The TLB must be invalidated if you remove an entry from
//     the page table.
//
// Hint: The TA solution is implemented using page_lookup,
// 	tlb_invalidate, and page_decref.
//
void
page_remove(pde_t *pgdir, void *va)
{
	tlb_invalidate(pgdir, va);
	// Fill this function in
	pte_t *pte;
	struct PageInfo *pi = page_lookup(pgdir, va, &pte);
	if(!pi)
		return;
	page_decref(pi);
	tlb_invalidate(pgdir, va);
	*pte = 0;
}

//
// Invalidate a TLB entry, but only if the page tables being
// edited are the ones currently in use by the processor.
//
void
tlb_invalidate(pde_t *pgdir, void *va)
{
	// Flush the entry only if we're modifying the current address space.
	if (!curenv || curenv->env_pgdir == pgdir)
		invlpg(va);
}

//
// Reserve size bytes in the MMIO region and map [pa,pa+size) at this
// location.  Return the base of the reserved region.  size does *not*
// have to be multiple of PGSIZE.
//
void *
mmio_map_region(physaddr_t pa, size_t size)
{
	// Where to start the next region.  Initially, this is the
	// beginning of the MMIO region.  Because this is static, its
	// value will be preserved between calls to mmio_map_region
	// (just like nextfree in boot_alloc).
	static uintptr_t base = MMIOBASE;

	// Reserve size bytes of virtual memory starting at base and
	// map physical pages [pa,pa+size) to virtual addresses
	// [base,base+size).  Since this is device memory and not
	// regular DRAM, you'll have to tell the CPU that it isn't
	// safe to cache access to this memory.  Luckily, the page
	// tables provide bits for this purpose; simply create the
	// mapping with PTE_PCD|PTE_PWT (cache-disable and
	// write-through) in addition to PTE_W.  (If you're interested
	// in more details on this, see section 10.5 of IA32 volume
	// 3A.)
	//
	// Be sure to round size up to a multiple of PGSIZE and to
	// handle if this reservation would overflow MMIOLIM (it's
	// okay to simply panic if this happens).
	//
	// Hint: The staff solution uses boot_map_region.
	//
	// Your code here:
	assert(pa % PGSIZE == 0);
	size = ROUNDUP(size, PGSIZE);
	if(base + size > MMIOLIM)
		panic("mmio_map_region: overflow MMIOLIM\n");
	void *ret = (void *) base;
	//static void boot_map_region(pde_t *pgdir, uintptr_t va, size_t size, physaddr_t pa, int perm);
	boot_map_region(kern_pgdir, base, size, pa, PTE_PCD | PTE_PWT | PTE_W | PTE_P);
	base += size;
	//panic("mmio_map_region not implemented");
	return ret;
}

// [begin, end]
int
pgdir_reperm(pde_t *pgdir, int old_perm, int new_perm, void *begin, void *end)
{
	// if(!(old_perm & PTE_SYSCALL)) return -E_INVAL;
	// if(!(new_perm & PTE_SYSCALL) && new_perm) return -E_INVAL;
	if((old_perm & -old_perm) != old_perm) return -E_INVAL;
	if((new_perm & -new_perm) != new_perm) return -E_INVAL;
	// cprintf("REPERM %p to %p\n", begin, end);
	begin = ROUNDDOWN(begin, PGSIZE);
	end = ROUNDDOWN(end, PGSIZE);
	if(begin > end) return -E_INVAL;
	int ret = 0;
	for(void *cur = begin;; cur += PGSIZE)
	{
		// cprintf("REPERM %p\n", cur);
		pte_t *pte = pgdir_walk(pgdir, cur, 0);
		if(pte && (*pte & old_perm))
		{
			*pte = (*pte & ~old_perm) | new_perm;
			++ret;
		}
		if(cur == end) break;
	}
	// cprintf("REPERM END %d\n", ret);
	return ret;
}

/*static void
rebuild_free_list()
{
	page_free_list = NULL;
	for(int i = npages - 1; i >= 0; i--)
		if(pages[i].pp_ref)
			pages[i].pp_link = NULL;
		else
		{
			pages[i].pp_link = page_free_list;
			page_free_list = &pages[i];
		}
}*/

/*static int
rand()
{
	static unsigned a = 233u;
	a = a * 1103515245u + 12345u;
	return (int) a & 0x7fffffff;
}

static bool
cmp_pos(struct PagePos *a, struct PagePos *b)
{
	if(a->min_envid != b->min_envid) return a->min_envid < b->min_envid;
	return a->v < b->v;
}

static void
qsort_pages_target_inv(int l, int r)
{
	for(int i = l; i <= r; i++)
	{
		if(!(pages[i].pp_ref && pages[i].pos.v == (void *) -1)) break;
		if(i == r) return;
	}
	int i = l, j = r;
	int xi;
	do
		xi = l + rand() % (r - l + 1);
	while(pages[xi].pp_ref && pages[xi].pos.v == (void *) -1);
	struct PagePos x = pages[pages[xi].target_pp_inv].pos;
	do
	{
		while((pages[i].pp_ref && pages[i].pos.v == (void *) -1)
			|| cmp_pos(&pages[pages[i].target_pp_inv].pos, &x))
			if(++i > r) break;
		while((pages[j].pp_ref && pages[j].pos.v == (void *) -1)
			|| cmp_pos(&x, &pages[pages[j].target_pp_inv].pos))
			if(--j < l) break;
		if(i <= j)
		{
			int y = pages[i].target_pp_inv;
			pages[i].target_pp_inv = pages[j].target_pp_inv;
			pages[j].target_pp_inv = y;
			++i; --j;
		}
	}
	while(i <= j);
	if(l < j) qsort_pages_target_inv(l, j);
	if(i < r) qsort_pages_target_inv(i, r);
}

static void
pages_apply_target()
{
	for(int i = 0; i < NENV; i++)
		if(envs[i].env_status != ENV_FREE)
		{
			pde_t *pde = envs[i].env_pgdir;
			for(int j = 0; j < UTOP / PTSIZE; j++)
				if(pde[j] & PTE_P)
				{
					for(void *va = (void *) (j * PTSIZE); va < (void *) ((j + 1) * PTSIZE); va += PGSIZE)
					{
						if(va >= (void *) UTOP) break;
						pte_t *pte;
						struct PageInfo *pp = page_lookup(envs[i].env_pgdir, va, &pte);
						if(pp)
						{
							assert(pp->target_pp >= 0);
							*pte = (pp->target_pp * PGSIZE) | (*pte & 0xfff);
						}
					}
					*pde = (pages[*pde >> 12].target_pp * PGSIZE) | (*pde & 0xfff);
				}
			envs[i].env_pgdir = KADDR(pages[PADDR(pde) >> 12].target_pp * PGSIZE);
		}
	while(1)
	{
		bool ok = 1;
		for(size_t i = 0; i < npages; i++)
		{
			if(!pages[i].pp_ref) continue;
			size_t j = pages[i].target_pp;
			if(i == j) continue;
			ok = 0;
			// TODO: switch to physical mode
			// cprintf("swap %d %d\n", i, j);
			boot_map_region(kern_pgdir, 0, PGSIZE, i * PGSIZE, PTE_W);
			boot_map_region(kern_pgdir, PGSIZE, PGSIZE, j * PGSIZE, PTE_W);
			invlpg(0);
			invlpg((void *) PGSIZE);
			static char tmp_page[PGSIZE];
			void *pi = (void *) 0, *pj = (void *) PGSIZE;
			memcpy(tmp_page, pi, PGSIZE);
			memcpy(pi, pj, PGSIZE);
			memcpy(pj, tmp_page, PGSIZE);
			
			struct PageInfo tmp = pages[i];
			pages[i] = pages[j]; pages[j] = tmp;
		}
		if(ok) break;
	}
	rebuild_free_list();
}*/

void
pmem_defrag()
{
	return;
	/*lcr3(PADDR(kern_pgdir));
	cprintf("DEFRAG:  begin\n");
	for(size_t i = 0; i < npages; i++)
	{
		pages[i].pos.min_envid = 0x7fffffff;
		pages[i].pos.v = (void *) -1;
	}
	for(int i = 0; i < NENV; i++)
		if(envs[i].env_status != ENV_FREE)
		{
			pde_t *pde = envs[i].env_pgdir;
			for(int j = 0; j < UTOP / PTSIZE; j++)
				if(pde[j] & PTE_P)
				{
					for(void *va = (void *) (j * PTSIZE); va < (void *) ((j + 1) * PTSIZE); va += PGSIZE)
					{
						if(va >= (void *) UTOP) break;
						struct PageInfo *pp = page_lookup(envs[i].env_pgdir, va, NULL);
						if(pp && envs[i].env_id < pp->pos.min_envid)
						{
							pp->pos.min_envid = envs[i].env_id;
							pp->pos.v = va;
						}
					}
					// pages[*pde >> 12].pos.min_envid = 1;
					// pages[*pde >> 12].pos.v = (void *) (i * 1024 + j);
				}
			// pages[PADDR(pde) >> 12].pos.min_envid = 0;
			// pages[PADDR(pde) >> 12].pos.v = (void *) i;
		}
	// for(size_t i = 0; i < npages; i++)
		// if(pages[i].pp_ref && pages[i].v == (void *) -1)
			// cprintf("wow %p\n", i * PGSIZE);
	// cprintf("total %p\n", npages * PGSIZE);
	for(size_t i = 0; i < npages; i++)
		++pages[i].pos.min_envid;
	for(size_t i = 0; i < npages; i++)
		pages[i].target_pp_inv = i;
	qsort_pages_target_inv(0, npages - 1);
	for(size_t i = 0; i < npages; i++)
		pages[pages[i].target_pp_inv].target_pp = i;
	// for(int i = npages - 1, j = npages - 1; i >= 0; i--)
	// {
		// while(pages[j].pp_ref && pages[j].pos.v == (void *) -1) --j;
		// if(pages[i].pp_ref && pages[i].pos.v != (void *) -1) pages[i].target_pp = j--;
		// else if(pages[i].pp_ref) pages[i].target_pp = i;
		// else pages[i].target_pp = -233;
	// }
	cprintf("DEFRAG:  applying...\n");
	pages_apply_target();
	cprintf("DEFRAG:  OK!\n");
	lcr3(PADDR(curenv->env_pgdir));*/
}

static uintptr_t user_mem_check_addr;

//
// Check that an environment is allowed to access the range of memory
// [va, va+len) with permissions 'perm | PTE_P'.
// Normally 'perm' will contain PTE_U at least, but this is not required.
// 'va' and 'len' need not be page-aligned; you must test every page that
// contains any of that range.  You will test either 'len/PGSIZE',
// 'len/PGSIZE + 1', or 'len/PGSIZE + 2' pages.
//
// A user program can access a virtual address if (1) the address is below
// ULIM, and (2) the page table gives it permission.  These are exactly
// the tests you should implement here.
//
// If there is an error, set the 'user_mem_check_addr' variable to the first
// erroneous virtual address.
//
// Returns 0 if the user program can access this range of addresses,
// and -E_FAULT otherwise.
//
int
user_mem_check(struct Env *env, const void *va, size_t len, int perm)
{
	// LAB 3: Your code here.
	const void *begin = ROUNDDOWN(va, PGSIZE);
	const void *end = ROUNDUP(va + len, PGSIZE);
	for(const void *i = begin; i != end; i += PGSIZE)
	{
		pte_t *pte = pgdir_walk(env->env_pgdir, i, 0);
		if(i >= (void *) ULIM || !pte || !(*pte & (perm | PTE_P)))
		{
			const void *ans = i;
			if(ans < va) ans = va;
			user_mem_check_addr = (uintptr_t) ans;
			return -E_FAULT;
		}
	}
	return 0;
}

//
// Checks that environment 'env' is allowed to access the range
// of memory [va, va+len) with permissions 'perm | PTE_U | PTE_P'.
// If it can, then the function simply returns.
// If it cannot, 'env' is destroyed and, if env is the current
// environment, this function will not return.
//
void
user_mem_assert(struct Env *env, const void *va, size_t len, int perm)
{
	if (user_mem_check(env, va, len, perm | PTE_U) < 0) {
		cprintf("[%08x] user_mem_check assertion failure for "
			"va %08x\n", env->env_id, user_mem_check_addr);
		env_destroy(env);	// may not return
	}
}


// --------------------------------------------------------------
// Checking functions.
// --------------------------------------------------------------

//
// Check that the pages on the page_free_list are reasonable.
//
static void
check_page_free_list(bool only_low_memory)
{
	return;
	/*struct PageInfo *pp;
	unsigned pdx_limit = only_low_memory ? 1 : NPDENTRIES;
	int nfree_basemem = 0, nfree_extmem = 0;
	char *first_free_page;

	if (!page_free_list)
		panic("'page_free_list' is a null pointer!");

	if (only_low_memory) {
		// Move pages with lower addresses first in the free
		// list, since entry_pgdir does not map all pages.
		struct PageInfo *pp1, *pp2;
		struct PageInfo **tp[2] = { &pp1, &pp2 };
		for (pp = page_free_list; pp; pp = pp->pp_link) {
			int pagetype = PDX(page2pa(pp)) >= pdx_limit;
			*tp[pagetype] = pp;
			tp[pagetype] = &pp->pp_link;
		}
		*tp[1] = 0;
		*tp[0] = pp2;
		page_free_list = pp1;
	}

	// if there's a page that shouldn't be on the free list,
	// try to make sure it eventually causes trouble.
	for (pp = page_free_list; pp; pp = pp->pp_link)
		if (PDX(page2pa(pp)) < pdx_limit)
			memset(page2kva(pp), 0x97, 128);

	first_free_page = (char *) boot_alloc(0);
	for (pp = page_free_list; pp; pp = pp->pp_link) {
		// check that we didn't corrupt the free list itself
		assert(pp >= pages);
		assert(pp < pages + npages);
		assert(((char *) pp - (char *) pages) % sizeof(*pp) == 0);

		// check a few pages that shouldn't be on the free list
		assert(page2pa(pp) != 0);
		assert(page2pa(pp) != IOPHYSMEM);
		assert(page2pa(pp) != EXTPHYSMEM - PGSIZE);
		assert(page2pa(pp) != EXTPHYSMEM);
		assert(page2pa(pp) < EXTPHYSMEM || (char *) page2kva(pp) >= first_free_page);
		// (new test for lab 4)
		assert(page2pa(pp) != MPENTRY_PADDR);

		if (page2pa(pp) < EXTPHYSMEM)
			++nfree_basemem;
		else
			++nfree_extmem;
	}

	assert(nfree_basemem > 0);
	assert(nfree_extmem > 0);

	cprintf("check_page_free_list() succeeded!\n");*/
}

//
// Check the physical page allocator (page_alloc(), page_free(),
// and page_init()).
//
static void
check_page_alloc(void)
{
	return;
	/*struct PageInfo *pp, *pp0, *pp1, *pp2;
	int nfree;
	struct PageInfo *fl;
	char *c;
	int i;

	if (!pages)
		panic("'pages' is a null pointer!");

	// check number of free pages
	for (pp = page_free_list, nfree = 0; pp; pp = pp->pp_link)
		++nfree;

	// should be able to allocate three pages
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));

	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);
	assert(page2pa(pp0) < npages*PGSIZE);
	assert(page2pa(pp1) < npages*PGSIZE);
	assert(page2pa(pp2) < npages*PGSIZE);

	// temporarily steal the rest of the free pages
	fl = page_free_list;
	page_free_list = 0;

	// should be no free memory
	assert(!page_alloc(0));

	// free and re-allocate?
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));
	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);
	assert(!page_alloc(0));

	// test flags
	memset(page2kva(pp0), 1, PGSIZE);
	page_free(pp0);
	assert((pp = page_alloc(ALLOC_ZERO)));
	assert(pp && pp0 == pp);
	c = page2kva(pp);
	for (i = 0; i < PGSIZE; i++)
		assert(c[i] == 0);

	// give free list back
	page_free_list = fl;

	// free the pages we took
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);

	// number of free pages should be the same
	for (pp = page_free_list; pp; pp = pp->pp_link)
		--nfree;
	assert(nfree == 0);

	cprintf("check_page_alloc() succeeded!\n");*/
}

//
// Checks that the kernel part of virtual address space
// has been setup roughly correctly (by mem_init()).
//
// This function doesn't test every corner case,
// but it is a pretty good sanity check.
//

static void
check_kern_pgdir(void)
{
	return;
	/*uint32_t i, n;
	pde_t *pgdir;

	pgdir = kern_pgdir;

	// check pages array
	n = ROUNDUP(npages*sizeof(struct PageInfo), PGSIZE);
	for (i = 0; i < n; i += PGSIZE)
		assert(check_va2pa(pgdir, UPAGES + i) == PADDR(pages) + i);

	// check envs array (new test for lab 3)
	n = ROUNDUP(NENV*sizeof(struct Env), PGSIZE);
	for (i = 0; i < n; i += PGSIZE)
		assert(check_va2pa(pgdir, UENVS + i) == PADDR(envs) + i);

	// check phys mem
	for (i = 0; i < npages * PGSIZE; i += PGSIZE)
		assert(check_va2pa(pgdir, KERNBASE + i) == i);

	// check kernel stack
	// (updated in lab 4 to check per-CPU kernel stacks)
	for (n = 0; n < NCPU; n++) {
		uint32_t base = KSTACKTOP - (KSTKSIZE + KSTKGAP) * (n + 1);
		for (i = 0; i < KSTKSIZE; i += PGSIZE)
			assert(check_va2pa(pgdir, base + KSTKGAP + i)
				== PADDR(percpu_kstacks[n]) + i);
		for (i = 0; i < KSTKGAP; i += PGSIZE)
			assert(check_va2pa(pgdir, base + i) == ~0);
	}

	// check PDE permissions
	for (i = 0; i < NPDENTRIES; i++) {
		switch (i) {
		case PDX(UVPT):
		case PDX(KSTACKTOP-1):
		case PDX(UPAGES):
		case PDX(UENVS):
		case PDX(MMIOBASE):
			assert(pgdir[i] & PTE_P);
			break;
		default:
			if (i >= PDX(KERNBASE)) {
				assert(pgdir[i] & PTE_P);
				assert(pgdir[i] & PTE_W);
			} else
				assert(pgdir[i] == 0);
			break;
		}
	}
	cprintf("check_kern_pgdir() succeeded!\n");*/
}

// This function returns the physical address of the page containing 'va',
// defined by the page directory 'pgdir'.  The hardware normally performs
// this functionality for us!  We define our own version to help check
// the check_kern_pgdir() function; it shouldn't be used elsewhere.

static physaddr_t
check_va2pa(pde_t *pgdir, uintptr_t va)
{
	pte_t *p;

	pgdir = &pgdir[PDX(va)];
	if (!(*pgdir & PTE_P))
		return ~0;
	p = (pte_t*) KADDR(PTE_ADDR(*pgdir));
	if (!(p[PTX(va)] & PTE_P))
		return ~0;
	return PTE_ADDR(p[PTX(va)]);
}


// check page_insert, page_remove, &c
static void
check_page(void)
{
	return;
	/*struct PageInfo *pp, *pp0, *pp1, *pp2;
	struct PageInfo *fl;
	pte_t *ptep, *ptep1;
	void *va;
	uintptr_t mm1, mm2;
	int i;
	extern pde_t entry_pgdir[];

	// should be able to allocate three pages
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));

	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);

	// temporarily steal the rest of the free pages
	fl = page_free_list;
	page_free_list = 0;

	// should be no free memory
	assert(!page_alloc(0));

	// there is no page allocated at address 0
	assert(page_lookup(kern_pgdir, (void *) 0x0, &ptep) == NULL);

	// there is no free memory, so we can't allocate a page table
	assert(page_insert(kern_pgdir, pp1, 0x0, PTE_W) < 0);

	// free pp0 and try again: pp0 should be used for page table
	page_free(pp0);
	assert(page_insert(kern_pgdir, pp1, 0x0, PTE_W) == 0);
	assert(PTE_ADDR(kern_pgdir[0]) == page2pa(pp0));
	assert(check_va2pa(kern_pgdir, 0x0) == page2pa(pp1));
	assert(pp1->pp_ref == 1);
	assert(pp0->pp_ref == 1);

	// should be able to map pp2 at PGSIZE because pp0 is already allocated for page table
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W) == 0);
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp2));
	assert(pp2->pp_ref == 1);

	// should be no free memory
	assert(!page_alloc(0));

	// should be able to map pp2 at PGSIZE because it's already there
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W) == 0);
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp2));
	assert(pp2->pp_ref == 1);

	// pp2 should NOT be on the free list
	// could happen in ref counts are handled sloppily in page_insert
	assert(!page_alloc(0));

	// check that pgdir_walk returns a pointer to the pte
	ptep = (pte_t *) KADDR(PTE_ADDR(kern_pgdir[PDX(PGSIZE)]));
	assert(pgdir_walk(kern_pgdir, (void*)PGSIZE, 0) == ptep+PTX(PGSIZE));

	// should be able to change permissions too.
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W|PTE_U) == 0);
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp2));
	assert(pp2->pp_ref == 1);
	assert(*pgdir_walk(kern_pgdir, (void*) PGSIZE, 0) & PTE_U);
	assert(kern_pgdir[0] & PTE_U);

	// should be able to remap with fewer permissions
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W) == 0);
	assert(*pgdir_walk(kern_pgdir, (void*) PGSIZE, 0) & PTE_W);
	assert(!(*pgdir_walk(kern_pgdir, (void*) PGSIZE, 0) & PTE_U));

	// should not be able to map at PTSIZE because need free page for page table
	assert(page_insert(kern_pgdir, pp0, (void*) PTSIZE, PTE_W) < 0);

	// insert pp1 at PGSIZE (replacing pp2)
	assert(page_insert(kern_pgdir, pp1, (void*) PGSIZE, PTE_W) == 0);
	assert(!(*pgdir_walk(kern_pgdir, (void*) PGSIZE, 0) & PTE_U));

	// should have pp1 at both 0 and PGSIZE, pp2 nowhere, ...
	assert(check_va2pa(kern_pgdir, 0) == page2pa(pp1));
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp1));
	// ... and ref counts should reflect this
	assert(pp1->pp_ref == 2);
	assert(pp2->pp_ref == 0);

	// pp2 should be returned by page_alloc
	assert((pp = page_alloc(0)) && pp == pp2);

	// unmapping pp1 at 0 should keep pp1 at PGSIZE
	page_remove(kern_pgdir, 0x0);
	assert(check_va2pa(kern_pgdir, 0x0) == ~0);
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp1));
	assert(pp1->pp_ref == 1);
	assert(pp2->pp_ref == 0);

	// test re-inserting pp1 at PGSIZE
	assert(page_insert(kern_pgdir, pp1, (void*) PGSIZE, 0) == 0);
	assert(pp1->pp_ref);
	assert(pp1->pp_link == NULL);

	// unmapping pp1 at PGSIZE should free it
	page_remove(kern_pgdir, (void*) PGSIZE);
	assert(check_va2pa(kern_pgdir, 0x0) == ~0);
	assert(check_va2pa(kern_pgdir, PGSIZE) == ~0);
	assert(pp1->pp_ref == 0);
	assert(pp2->pp_ref == 0);

	// so it should be returned by page_alloc
	assert((pp = page_alloc(0)) && pp == pp1);

	// should be no free memory
	assert(!page_alloc(0));

	// forcibly take pp0 back
	assert(PTE_ADDR(kern_pgdir[0]) == page2pa(pp0));
	kern_pgdir[0] = 0;
	assert(pp0->pp_ref == 1);
	pp0->pp_ref = 0;

	// check pointer arithmetic in pgdir_walk
	page_free(pp0);
	va = (void*)(PGSIZE * NPDENTRIES + PGSIZE);
	ptep = pgdir_walk(kern_pgdir, va, 1);
	ptep1 = (pte_t *) KADDR(PTE_ADDR(kern_pgdir[PDX(va)]));
	assert(ptep == ptep1 + PTX(va));
	kern_pgdir[PDX(va)] = 0;
	pp0->pp_ref = 0;

	// check that new page tables get cleared
	memset(page2kva(pp0), 0xFF, PGSIZE);
	page_free(pp0);
	pgdir_walk(kern_pgdir, 0x0, 1);
	ptep = (pte_t *) page2kva(pp0);
	for(i=0; i<NPTENTRIES; i++)
		assert((ptep[i] & PTE_P) == 0);
	kern_pgdir[0] = 0;
	pp0->pp_ref = 0;

	// give free list back
	page_free_list = fl;

	// free the pages we took
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);

	// test mmio_map_region
	mm1 = (uintptr_t) mmio_map_region(0, 4097);
	mm2 = (uintptr_t) mmio_map_region(0, 4096);
	// check that they're in the right region
	assert(mm1 >= MMIOBASE && mm1 + 8096 < MMIOLIM);
	assert(mm2 >= MMIOBASE && mm2 + 8096 < MMIOLIM);
	// check that they're page-aligned
	assert(mm1 % PGSIZE == 0 && mm2 % PGSIZE == 0);
	// check that they don't overlap
	assert(mm1 + 8096 <= mm2);
	// check page mappings
	assert(check_va2pa(kern_pgdir, mm1) == 0);
	assert(check_va2pa(kern_pgdir, mm1+PGSIZE) == PGSIZE);
	assert(check_va2pa(kern_pgdir, mm2) == 0);
	assert(check_va2pa(kern_pgdir, mm2+PGSIZE) == ~0);
	// check permissions
	assert(*pgdir_walk(kern_pgdir, (void*) mm1, 0) & (PTE_W|PTE_PWT|PTE_PCD));
	assert(!(*pgdir_walk(kern_pgdir, (void*) mm1, 0) & PTE_U));
	// clear the mappings
	*pgdir_walk(kern_pgdir, (void*) mm1, 0) = 0;
	*pgdir_walk(kern_pgdir, (void*) mm1 + PGSIZE, 0) = 0;
	*pgdir_walk(kern_pgdir, (void*) mm2, 0) = 0;

	cprintf("check_page() succeeded!\n");*/
}

// check page_insert, page_remove, &c, with an installed kern_pgdir
static void
check_page_installed_pgdir(void)
{
	struct PageInfo *pp, *pp0, *pp1, *pp2;
	struct PageInfo *fl;
	pte_t *ptep, *ptep1;
	uintptr_t va;
	int i;

	// check that we can read and write installed pages
	pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));
	//cprintf("asdf %d %d %d\n", pp0->pp_ref, pp1->pp_ref, pp2->pp_ref);
	page_free(pp0);
	memset(page2kva(pp1), 1, PGSIZE);
	memset(page2kva(pp2), 2, PGSIZE);
	page_insert(kern_pgdir, pp1, (void*) PGSIZE, PTE_W);
	assert(pp1->pp_ref == 1);
	assert(*(uint32_t *)PGSIZE == 0x01010101U);
	page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W);
	assert(*(uint32_t *)PGSIZE == 0x02020202U);
	assert(pp2->pp_ref == 1);
	assert(pp1->pp_ref == 0);
	*(uint32_t *)PGSIZE = 0x03030303U;
	assert(*(uint32_t *)page2kva(pp2) == 0x03030303U);
	page_remove(kern_pgdir, (void*) PGSIZE);
	assert(pp2->pp_ref == 0);

	// forcibly take pp0 back
	assert(PTE_ADDR(kern_pgdir[0]) == page2pa(pp0));
	kern_pgdir[0] = 0;
	assert(pp0->pp_ref == 1);
	pp0->pp_ref = 0;

	// free the pages we took
	page_free(pp0);

	cprintf("check_page_installed_pgdir() succeeded!\n");
}
